base:
  format:
    coronavirus_landing_page: 2.5
    service_manual_guide: 0.3
    service_manual_topic: 0.3
    step_by_step_nav: 2.5
    transaction: 1.5
    smart_answer: 1.5
    # Should appear below govuk (mainstream) content
    aaib_report: 0.2
    research_for_development_output: 0.2
    hmrc_manual_section: 0.2
    service_standard_report: 0.05
    # Inside Gov formats
    contact: 0.3
    document_collection: 1.3
    document_series: 1.3
    minister: 1.7
    operational_field: 1.5
    organisation: 2.5
    topic: 1.5
    topical_event: 1.5
    # Hide mainstream browse pages
    mainstream_browse_page: 0
    # Topics
    specialist_sector: 2.5
  content_store_document_type:
    foi_release: 0.2
  navigation_document_supertype:
    guidance: 2.5
  search_user_need_document_supertype:
    core: 1.5
  organisation_state:
    closed: 0.2
    devolved: 0.3
  is_historic:
    true: 0.5
  part_of_taxonomy_tree:
    5b7b9532-a775-4bd2-a3aa-6ce380184b6c: 5 # /coronavirus-taxon
# Overrides to apply to the sitemap priorities in external search
external_search:
  format:
    mainstream_browse_page: 2
    policy: 1.5
    topic: 2
